version: '2'
services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    environment:
      URL: ""
      PORT: 8000
      DOCKER: "true"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"